### ISSUE TITLE
Segmentation fault and Cannot allocate memory

### ISSUE THREAD

**Issue by xiaogouaiyaotou** [the-data-lab/gstore#3]
Hello, it's me again. This time when I try to convert the file which generated by the generator you provided, it shows a "segmentation fault".
![WeChatb26088bc694f9427fbf684e0e99d6b26](https://user-images.githubusercontent.com/47123798/65456178-65c79d80-de0e-11e9-9940-cb08d066b455.png)
And when I use another small file to execute this command, it worked. But it still has trouble when I execute the next command.
![WeChat875e62a8808aabb48415b892b23b3292](https://user-images.githubusercontent.com/47123798/65456642-5f85f100-de0f-11e9-811a-bdc9546b5193.png)
Do you know what can cause these problems? Thank you!

**Comment by pradeep-k** [comment]
Do you want to use generator or G-Store?

**Comment by xiaogouaiyaotou** [comment]
Both. The generator worked well and already generate a file. It has a little bit trouble when I try to use it in G-Store.

**Comment by pradeep-k** [comment]
Okay, great. Just to be sure, I should not include GraphOne at all this issue. 
So, I will look it purely from the G-Store perspective. Give me some time, I will post the response.

**Comment by pradeep-k** [comment]
Just run the command using sudo, that is 

sudo ./gstoreu -s 25 -i xyz -j 1 -a 5

**Comment by xiaogouaiyaotou** [comment]
Yes, it actually worked for the small size datafile. But for the large size, it still shows me "segmentation fault" when I try to convert it.
![image](https://user-images.githubusercontent.com/47123798/65458891-45024680-de14-11e9-8a4b-c4282255aaab.png)

**Comment by pradeep-k** [comment]
I edited the response above. I changed the generator to generate text file based on the comments in GraphOne repository. I am updating the README of the generator, and g-store

**Comment by pradeep-k** [comment]
README has been updated

**Comment by xiaogouaiyaotou** [comment]
I already have some binary edge list files that can worked very well in other frameworks. The problem here seems like it can't process large file. For example, if I use the wiki-vote datasets http://snap.stanford.edu/data/wiki-Vote.html which only includes 7115 nodes, it can convert very good. But, if I use some big datasets, like LiverJournal or larger, it will show me a "segmentation fault".

**Comment by pradeep-k** [comment]
I want you to share the link of the data that produces a segmentation error. 

The problem could be -s argument. You should use -s (log2 of vertex count ) or -v (actual vertex count) argument, which specifies the number of vertices. Are you using -s 25 all the time? That may be a problem.

**Comment by xiaogouaiyaotou** [comment]
http://snap.stanford.edu/data/soc-LiveJournal1.html This is the link of LiveJournal. I changed the parameter -s, and it works very strange. This dataset only has 4847571 nodes, I think set a 25 for -s is enough. And it didn't work until I changed the -s to 30. And if I set the actual nodes to -v, it didn't work neither. 
![image](https://user-images.githubusercontent.com/47123798/65466334-1e4c0c00-de24-11e9-94b5-cdd0646f226b.png)

**Comment by pradeep-k** [comment]
You didn't convert the live journal text graph file to binary file. Gstore only accepts binary file to convert it to our internal format.  Please read the updated readme for gstore.

I should have provided a way to directly convert text file to our format, but unfortunately I don't have that. We are integrating gstore format with GraphOne. But till then, convert text file to binary file using -c4 option, followed by -c1 option to convert the binary file to gstore format, then run all the analytics.

**Comment by xiaogouaiyaotou** [comment]
No sir, I did it. The file ending in .edge is I converted by your convertor. I just didn't show this step in the picture.

**Comment by pradeep-k** [comment]
I am able to use the G-Store without any changes. Here is the log. See the details about vertex count thing in the log:

```
pkumar@mira:/mnt/data$ wget http://snap.stanford.edu/data/soc-LiveJournal1.txt.gz
--2019-09-24 19:56:12--  http://snap.stanford.edu/data/soc-LiveJournal1.txt.gz
Resolving snap.stanford.edu (snap.stanford.edu)... 171.64.75.80
Connecting to snap.stanford.edu (snap.stanford.edu)|171.64.75.80|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 259619239 (248M) [application/x-gzip]
Saving to: ‘soc-LiveJournal1.txt.gz’

soc-LiveJournal1.txt.gz                                                100%[==========================================================================================================================================================================>] 247.59M  11.2MB/s    in 50s     

2019-09-24 19:57:02 (4.94 MB/s) - ‘soc-LiveJournal1.txt.gz’ saved [259619239/259619239]

pkumar@mira:/mnt/data$ ls -lh
total 248M
-rw-r--r-- 1 pkumar pkumar 248M Dec  2  2009 soc-LiveJournal1.txt.gz
pkumar@mira:/mnt/data$ gunzip soc-LiveJournal1.txt.gz 
pkumar@mira:/mnt/data$ ls
soc-LiveJournal1.txt
pkumar@mira:/mnt/data$ head soc-LiveJournal1.txt 
# Directed graph (each unordered pair of nodes is saved once): soc-LiveJournal1.txt 
# Directed LiveJournal friednship social network
# Nodes: 4847571 Edges: 68993773
# FromNodeId	ToNodeId
0	1
0	2
0	3
0	4
0	5
0	6
pkumar@mira:~/src/gstore$ ./gstoreu -c 4 -i /mnt/data/soc-LiveJournal1.txt 
Total Physcial Group Count (in One Direction) = 0
Total Tiles Count (in One Direction) = 0
max vertex id: 68993773
min vertex id: 0
edge count: 68993786
vert count: 68993774                        <======== vertex count
pkumar@mira:~/src/gstore$ tail /mnt/data/soc-LiveJournal1.txt
4847570	19501
4847570	90409
4847570	341538
4847570	403089
4847570	476643
4847570	476973
4847570	525852
4847570	537376
4847570	4847564
4847570	4847570
pkumar@mira:~/src/gstore$ ./gstoreu -s 25 -i /mnt/data/soc-LiveJournal1.txt.edge -c 1 -o /mnt/data/soc-LiveJournal1.dat  <==== Wrong vertex count, as -s 25 is less than 68993774
Total Physcial Group Count (in One Direction) = 2
Total Tiles Count (in One Direction) = 512
Total edges = 68518933
Segmentation fault (core dumped)
pkumar@mira:~/src/gstore$ ./gstoreu -v 68993774 -i /mnt/data/soc-LiveJournal1.txt.edge -c 1 -o /mnt/data/soc-LiveJournal1.dat    <=== correct v count
Total Physcial Group Count (in One Direction) = 5
Total Tiles Count (in One Direction) = 1280
Total edges = 68518934
classifcation done
GStore Conversion Time = 0.630569
save grid start
Total Edges again = 68518934
Compressing degree start
1
Compressing done
saving done
GStore Time = 0.818871
pkumar@mira:~/src/gstore$ sudo ./gstoreu -v 68993774 -i /mnt/data/soc-LiveJournal1.dat -j 1 -a5 <===  need sudo due to mlock, I will fix it.
Total Physcial Group Count (in One Direction) = 5
Total Tiles Count (in One Direction) = 1280
edge_count = 68518934
memory size = 8589934592
segment size = 268435456
Cache size = 8053063680
memory partition count = 2
post-processing time = 5.28426
iteration time = 11.2477
post-processing time = 0.039814
iteration time = 0.320307
post-processing time = 0.039444
iteration time = 0.328483
post-processing time = 0.0396938
iteration time = 0.305006
post-processing time = 0.039542
iteration time = 0.314107
Page-rank time = 16.76
```

**Comment by xiaogouaiyaotou** [comment]
Ummm... I don't know why it suddenly worked. And I don't understand what the "half BFS time" means?
![image](https://user-images.githubusercontent.com/47123798/66784235-7ca66080-ee9f-11e9-9052-abe0e09e178f.png)

**Comment by pradeep-k** [comment]
Thanks for the update. 
Half BFS was printed just to emphasize that G-Store[SC'16] stores graph data in one direction only. So, for undirected graphs, we only store in one direction, by storing the upper triangle (or lower triangle), and out-edge (or in-edges) for directed graphs. Our tile and SNB representation can take care of the need to access graph in other directions.

Kindly read the paper on how we take advantage of symmetry in graph data.

Thank you again, I will be closing the issue. Feel free to raise a new one, or send me an email.
